<?php

namespace Timbrs\DatabaseDumps\Platform;

use Timbrs\DatabaseDumps\Contract\DatabaseConnectionInterface;
use Timbrs\DatabaseDumps\Contract\LoggerInterface;

/**
 * Платформа Oracle (12c+)
 */
class OraclePlatform extends AbstractPlatform
{
    /** @var LoggerInterface|null */
    private $logger;

    public function __construct(LoggerInterface $logger = null)
    {
        $this->logger = $logger;
    }

    protected function getIdentifierQuote(): string
    {
        return '"';
    }

    /**
     * Oracle хранит unquoted идентификаторы в UPPERCASE. В quoted-виде регистр значим.
     * По соглашению библиотеки мы оборачиваем имена в кавычки и приводим к UPPER,
     * чтобы соответствовать стандартным таблицам.
     *
     * Для случая когда таблица была создана как `CREATE TABLE "users"` (lowercase в кавычках),
     * нужно передавать имя в требуемом регистре в YAML — конкатенации не происходит.
     */
    protected function normalizeIdentifier(string $identifier): string
    {
        return strtoupper($identifier);
    }

    /**
     * Oracle не поддерживает TRUNCATE ... CASCADE, поэтому используем DELETE FROM.
     * Управление FK-constraints предполагается через before_exec/after_exec скрипты.
     */
    public function getTruncateStatement(string $schema, string $table): string
    {
        return 'DELETE FROM ' . $this->getFullTableName($schema, $table) . ';';
    }

    /**
     * Сброс sequence через DDL (StatementSplitter их корректно разделяет по ;):
     *   - Identity-колонки (12c+): ALTER TABLE MODIFY (col GENERATED AS IDENTITY START WITH N)
     *   - Sequence по соглашению имени (TABLE_SEQ или table_id_seq): ALTER SEQUENCE ... RESTART START WITH N
     */
    public function getSequenceResetSql(string $schema, string $table, DatabaseConnectionInterface $connection): string
    {
        $sql = "-- Сброс sequences/identity\n";

        try {
            $upperSchema = strtoupper($schema);
            $upperTable = strtoupper($table);
            $fullTable = $this->getFullTableName($schema, $table);

            // 1. Identity-колонки (Oracle 12c+)
            $identityCols = $connection->fetchAllAssociative(
                "SELECT column_name FROM all_tab_identity_cols
                 WHERE owner = :owner AND table_name = :table",
                ['owner' => $upperSchema, 'table' => $upperTable]
            );

            foreach ($identityCols as $row) {
                $col = $row['column_name'];
                $quotedCol = $this->quoteIdentifier($col);
                $maxRow = $connection->fetchAllAssociative(
                    "SELECT NVL(MAX({$quotedCol}), 0) + 1 AS next_value FROM {$fullTable}"
                );
                $next = isset($maxRow[0]['next_value']) ? (int) $maxRow[0]['next_value'] : 1;

                // ALTER TABLE ... MODIFY (col GENERATED AS IDENTITY (START WITH N))
                $sql .= "ALTER TABLE {$fullTable} MODIFY ({$quotedCol} "
                    . "GENERATED BY DEFAULT AS IDENTITY (START WITH {$next}));\n";
            }

            // 2. Sequence по соглашению имени (без жёсткой проверки PK)
            $candidates = [
                $upperTable . '_SEQ',
                $upperTable . '_ID_SEQ',
                'SEQ_' . $upperTable,
            ];

            foreach ($candidates as $seqName) {
                $exists = $connection->fetchAllAssociative(
                    "SELECT 1 AS x FROM all_sequences
                     WHERE sequence_owner = :owner AND sequence_name = :seq",
                    ['owner' => $upperSchema, 'seq' => $seqName]
                );
                if (empty($exists)) {
                    continue;
                }
                // Берём MAX по первой числовой колонке таблицы — если таблица пуста, START WITH 1.
                $pkCol = $this->detectPrimaryNumericColumn($connection, $upperSchema, $upperTable);
                if ($pkCol === null) {
                    continue;
                }
                $quotedCol = $this->quoteIdentifier($pkCol);
                $maxRow = $connection->fetchAllAssociative(
                    "SELECT NVL(MAX({$quotedCol}), 0) + 1 AS next_value FROM {$fullTable}"
                );
                $next = isset($maxRow[0]['next_value']) ? (int) $maxRow[0]['next_value'] : 1;

                $quotedSeq = $this->quoteIdentifier($schema) . '.' . $this->quoteIdentifier($seqName);
                // Oracle 12c+: RESTART START WITH N — одностроковый DDL
                $sql .= "ALTER SEQUENCE {$quotedSeq} RESTART START WITH {$next};\n";
            }
        } catch (\Exception $e) {
            if ($this->logger !== null) {
                $this->logger->warning(
                    'Ошибка сброса Oracle sequences для ' . $schema . '.' . $table . ': ' . $e->getMessage()
                );
            }
            $sql .= "-- Не удалось сбросить sequences (детали в логе)\n";
        }

        return $sql;
    }

    public function getRandomFunctionSql(): string
    {
        return 'DBMS_RANDOM.VALUE';
    }

    public function getLimitSql(int $limit): string
    {
        return 'FETCH FIRST ' . $limit . ' ROWS ONLY';
    }

    public function supportsMultiRowInsert(): bool
    {
        return false;
    }

    public function quoteBoolean(bool $value): string
    {
        // Oracle < 23c не имеет нативного BOOLEAN — используется NUMBER(1)/CHAR(1)
        return $value ? '1' : '0';
    }

    /**
     * Найти первую NUMBER-колонку таблицы (как кандидат на PK для sequence reset).
     */
    private function detectPrimaryNumericColumn(
        DatabaseConnectionInterface $connection,
        string $owner,
        string $table
    ): ?string {
        $rows = $connection->fetchAllAssociative(
            "SELECT column_name FROM all_tab_columns
             WHERE owner = :owner AND table_name = :table AND data_type = 'NUMBER'
             ORDER BY column_id
             FETCH FIRST 1 ROWS ONLY",
            ['owner' => $owner, 'table' => $table]
        );

        if (empty($rows)) {
            return null;
        }

        return $rows[0]['column_name'];
    }
}
