<?php

namespace Timbrs\DatabaseDumps\Tests\Unit\Platform;

use PHPUnit\Framework\TestCase;
use Timbrs\DatabaseDumps\Contract\DatabaseConnectionInterface;
use Timbrs\DatabaseDumps\Platform\OraclePlatform;

class OraclePlatformTest extends TestCase
{
    /** @var OraclePlatform */
    private $platform;

    protected function setUp(): void
    {
        $this->platform = new OraclePlatform();
    }

    public function testQuoteIdentifierUppercases(): void
    {
        $this->assertSame('"ID"', $this->platform->quoteIdentifier('id'));
        $this->assertSame('"MY_TABLE"', $this->platform->quoteIdentifier('my_table'));
        $this->assertSame('"USERS"', $this->platform->quoteIdentifier('Users'));
    }

    public function testQuoteIdentifierEscapesInnerQuotes(): void
    {
        // Защита от инъекций: внутренние " удваиваются (и затем UPPER)
        $this->assertSame('"WEIRD""NAME"', $this->platform->quoteIdentifier('weird"name'));
    }

    public function testGetFullTableName(): void
    {
        $this->assertSame('"SCHEMA"."TABLE"', $this->platform->getFullTableName('schema', 'table'));
    }

    public function testGetTruncateStatementUsesDelete(): void
    {
        $sql = $this->platform->getTruncateStatement('users', 'users');
        $this->assertStringContainsString('DELETE FROM', $sql);
        $this->assertStringContainsString('"USERS"."USERS"', $sql);
        $this->assertStringNotContainsString('TRUNCATE', $sql);
        $this->assertStringNotContainsString('CASCADE', $sql);
    }

    public function testGetSequenceResetSqlGeneratesIdentityAlter(): void
    {
        // Identity-колонка
        $connection = $this->createMock(DatabaseConnectionInterface::class);
        $connection->method('fetchAllAssociative')->willReturnOnConsecutiveCalls(
            [['column_name' => 'id']],              // identity columns
            [['next_value' => 99]],                  // max for identity
            []                                       // no candidate sequences
        );

        $sql = $this->platform->getSequenceResetSql('public', 'users', $connection);

        $this->assertStringContainsString('ALTER TABLE', $sql);
        $this->assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY (START WITH 99)', $sql);
    }

    public function testGetSequenceResetSqlNoIdentityNoSequence(): void
    {
        $connection = $this->createMock(DatabaseConnectionInterface::class);
        $connection->method('fetchAllAssociative')->willReturn([]);

        $sql = $this->platform->getSequenceResetSql('public', 'users', $connection);
        // Если ничего не найдено — только заголовок-комментарий, без падений
        $this->assertStringContainsString('Сброс sequences/identity', $sql);
    }

    public function testSupportsMultiRowInsertIsFalse(): void
    {
        $this->assertFalse($this->platform->supportsMultiRowInsert());
    }

    public function testQuoteBooleanReturnsNumeric(): void
    {
        $this->assertSame('1', $this->platform->quoteBoolean(true));
        $this->assertSame('0', $this->platform->quoteBoolean(false));
    }

    public function testGetRandomFunctionSql(): void
    {
        $this->assertSame('DBMS_RANDOM.VALUE', $this->platform->getRandomFunctionSql());
    }

    public function testGetLimitSql(): void
    {
        $this->assertSame('FETCH FIRST 100 ROWS ONLY', $this->platform->getLimitSql(100));
        $this->assertSame('FETCH FIRST 1 ROWS ONLY', $this->platform->getLimitSql(1));
    }
}
